version: "3.8"

services:
  backend:
    image: marlburrow/cursor-chat:v1.0.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chat.rule=Host(`chat.marlburrow.io`)"
        - "traefik.http.routers.chat.entrypoints=websecure"
        - "traefik.http.routers.chat.tls.certresolver=le"
        - "traefik.http.services.chat.loadbalancer.server.port=3000" # 🔹 Ajout de cette ligne !
        - "traefik.docker.network=traefik-public"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chat
      - PORT=3000
    networks:
      - chat-network
      - traefik-public # 🔹 Ajout du réseau partagé avec Traefik !
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

networks:
  chat-network:
    driver: overlay
  traefik-public:
    external: true # 🔹 Utilisation du même réseau que Traefik !

volumes:
  mongodb_data:
    driver: local
